### ISSUE TITLE
Remove dependency on Zarf

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/maru-runner#23]
### Description
Today Maru pulls in Zarf for various action cmds. Remove the dependency on Zarf and migrate actions commands to this repo

**Comment by Racer159** [comment]
@UncleGedd just to tie things together, let me know what timeline / priority you're working this on, we should squish the things that I am working in this PR to make this clean: https://github.com/defenseunicorns/zarf/pull/2276
