### ISSUE TITLE
uds run task errors when deploying bundle from `../`

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/maru-runner#34]
### Environment

Device and OS: EC2 Instance - Amazon Linux 2
App version: v0.9.4
Kubernetes distro being used: EKS 1.27
Other:

### Steps to reproduce
This was noticed between v0.9.2 and v0.9.3 (migration to maru?)

1. Create a deploy yaml like this
```
tasks:
  - name: deploy-uds-bundle
    description: "Deploy the UDS Core Standard Bundle"
    actions:
      - cmd: "uds deploy ../uds-bundle-test-${UDS_ARCH}-${VERSION}.tar.zst --confirm --no-progress"
```
`uds run deploy-uds-bundle`

### Expected result
the uds bundle starts deploying
### Actual Result
```
 NOTE  Saving log file to /tmp/runner-2024-03-18-18-42-29-1105412261.log
     Error: unknown shorthand flag: 'b' in -bundle-test-amd64-0.0.1.tar.zst
     Usage:
       uds deploy [BUNDLE_TARBALL|OCI_REF] [flags]


     Error: unknown shorthand flag: 'b' in -bundle-test-amd64-0.0.1.tar.zst
     ERROR:  Failed to run action: command "uds deploy ../uds-bundle-test-amd64-0.0.1.tar.zst" timed out after 0
             seconds
```

seems to misinterpret `../uds` as a command or ignore it altogether?

### Additional Context

Add any other context or screenshots about the technical debt here.

**Comment by decleaver** [comment]
able to run the same cmd from the command line and it works fine, so something to do with how its being run in the runner. 🏃

**Comment by decleaver** [comment]
happens for all uds commands that you can provide a file to (deploy, inspect, remove..)
