### ISSUE TITLE
Implement Concurrent Action Execution in `executeTask`

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/maru-runner#85]
#### Summary
The current implementation of the [executeTask](fhttps://github.com/defenseunicorns/uds-cli/blob/343662d8e6bc555dea3ff63c1a5ed96081a88222/src/pkg/runner/runner.go#L211-L239) method in `runner.go` executes each action within a task sequentially. This approach ensures simplicity and straightforward execution flow but may not efficiently utilize system resources, especially when actions are independent and could be executed concurrently. This proposal suggests enhancing the [executeTask](https://github.com/defenseunicorns/uds-cli/blob/343662d8e6bc555dea3ff63c1a5ed96081a88222/src/pkg/runner/runner.go#L211-L239) method to support concurrent execution of actions, potentially improving performance and reducing task completion time.

#### Motivation
Tasks that contain multiple independent actions can benefit significantly from concurrent execution. In the current sequential execution model, the total execution time is the sum of all actions' execution times. By executing actions concurrently, we can reduce the total execution time to the duration of the longest-running action, assuming sufficient system resources. This improvement is particularly beneficial for tasks with many independent actions or tasks where actions are I/O bound and spend significant time waiting.

This should reduce the wait time to bootstrap an `env`

#### Proposed Changes
1. **Concurrency Model**: Utilize Go's concurrency model, leveraging goroutines and channels, to execute actions within a task concurrently.
2. **Error Handling**: Implement a mechanism to collect and handle errors from concurrently executed actions. This could involve aggregating errors and returning a composite error if multiple actions fail.
3. **Environment Variables Management**: Ensure that the setup of default environment variables ([defaultEnv](https://github.com/defenseunicorns/uds-cli/blob/343662d8e6bc555dea3ff63c1a5ed96081a88222/src/pkg/runner/runner.go#L218)) and task-specific environment variables (`task.EnvPath`) is thread-safe and correctly applied to each action executed concurrently.
4. **Dependency Management**: Introduce a way to specify dependencies between actions, if necessary. This could be important for tasks where certain actions must be executed in sequence due to dependencies.

#### Implementation Details
- Use a `sync.WaitGroup` to wait for all goroutines (actions) to complete.
- Use a buffered channel to collect errors from all concurrently executed actions. This channel allows us to aggregate errors and handle them appropriately after all actions have been executed.
- Ensure that the modification of any shared state (e.g., environment variables) is thread-safe. This may involve using mutexes or designing the system in a way that avoids shared mutable state.

#### Risks and Mitigations
- **Race Conditions**: Introducing concurrency can lead to race conditions if actions modify shared state. We will mitigate this risk by avoiding shared mutable state or using synchronization primitives (e.g., mutexes) where necessary.
- **Error Handling Complexity**: Concurrent execution makes error handling more complex, as multiple actions could fail simultaneously. We will address this by aggregating errors and ensuring that the user is informed of all issues that occur during task execution.
- **Resource Saturation**: Executing many actions concurrently could overwhelm system resources. We will mitigate this by allowing the user to configure the maximum number of concurrent actions, providing a balance between concurrency and resource utilization.

#### Prototype
```golang
func (r *Runner) executeTask(task types.Task) error {
    if len(task.Files) > 0 {
        if err := r.placeFiles(task.Files); err != nil {
            return err
        }
    }

    defaultEnv := []string{}
    for name, inputParam := range task.Inputs {
        d := inputParam.Default
        if d == "" {
            continue
        }
        defaultEnv = append(defaultEnv, formatEnvVar(name, d))
    }

    // load the tasks env file into the runner, can override previous task's env files
    if task.EnvPath != "" {
        r.envFilePath = task.EnvPath
    }

    // Use a WaitGroup to wait for all goroutines to finish
    var wg sync.WaitGroup
    // Channel to collect errors from goroutines
    errChan := make(chan error, len(task.Actions))

    for _, action := range task.Actions {
        wg.Add(1)
        go func(action types.Action) {
            defer wg.Done()
            action.Env = mergeEnv(action.Env, defaultEnv)
            if err := r.performAction(action); err != nil {
                errChan <- err
                return
            }
            errChan <- nil
        }(action)
    }

    // Wait for all actions to complete
    wg.Wait()
    close(errChan)

    // Check for errors
    for err := range errChan {
        if err != nil {
            return err // or accumulate errors if you prefer
        }
    }

    return nil
}
```
_not tested or compiled_

#### Conclusion
Adopting concurrent action execution in the `executeTask`method has the potential to significantly improve performance for tasks with multiple independent actions. By carefully managing the risks associated with concurrency, we can make the task execution process more efficient and responsive to user needs.

**Comment by Racer159** [comment]
closing in favor of  #138 #131 and #164 since these focus on some of the more specific changes
